use std::fmt::Write as _;
use std::fs::{self, OpenOptions};
use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use crate::catalog::{
    Catalog, CatalogError, Confidence, EvidenceLevel, Priority, Role, SelectionStatus,
};

static TEMPORARY_FILE_COUNTER: AtomicU64 = AtomicU64::new(0);

pub fn render_markdown(catalog: &Catalog) -> String {
    let mut artifacts: Vec<_> = catalog.artifact.iter().collect();
    artifacts.sort_by(|left, right| {
        left.role
            .cmp(&right.role)
            .then_with(|| {
                version_key(&left.stated_version).cmp(&version_key(&right.stated_version))
            })
            .then_with(|| left.source_path.cmp(&right.source_path))
    });

    let mut output = String::from(
        "<!-- Generated from 01-ARTIFACTS.toml. Do not edit this file. -->\n# Phase 1 Artifact Catalog\n\n",
    );

    render_selection_summary(&mut output, &artifacts);
    render_inspection_branch(&mut output, catalog);
    render_artifact_table(&mut output, &artifacts);
    render_selected_details(&mut output, &artifacts);
    render_hypotheses(&mut output, &artifacts);
    render_handoff(&mut output, catalog);
    output
}

fn render_inspection_branch(output: &mut String, catalog: &Catalog) {
    let branch = &catalog.inspection_branch;
    output.push_str("## Conditional Inspection Branch\n\n");
    let _ = writeln!(output, "- Manifest: `{}`", branch.manifest_path);
    let _ = writeln!(output, "- State: {}", branch.state);
    let _ = writeln!(output, "- Selected branch: {}", branch.selected_branch);
    let _ = writeln!(
        output,
        "- Windows XP summary: {}",
        branch.windows_xp_summary
    );
    for evidence in &branch.evidence {
        let _ = writeln!(output, "- Evidence: {}", markdown_text(evidence));
    }
    for item in &branch.output {
        let _ = writeln!(
            output,
            "- Output: `{}` from `{}` member `{}` at offset {} with length {} for `{}`",
            item.output_path,
            item.source_container,
            item.member,
            item.offset,
            item.length,
            item.artifact_id
        );
    }
    output.push('\n');
}

pub fn write_markdown(path: &Path, content: &str) -> Result<(), CatalogError> {
    let temporary_path = temporary_sibling_path(path)?;
    let result = write_complete_file(&temporary_path, content)
        .and_then(|()| fs::rename(&temporary_path, path));

    if let Err(source) = result {
        let _ = fs::remove_file(&temporary_path);
        return Err(io_error(path, source));
    }
    Ok(())
}

fn render_selection_summary(output: &mut String, artifacts: &[&crate::catalog::Artifact]) {
    output.push_str("## Selection Summary\n\n");
    for artifact in artifacts
        .iter()
        .filter(|artifact| artifact.selection_status != SelectionStatus::Unselected)
    {
        let _ = writeln!(
            output,
            "- {} {}: `{}` ({})",
            role_name(artifact.role),
            artifact.stated_version,
            artifact.id,
            selection_name(artifact.selection_status)
        );
    }
    output.push('\n');
}

fn render_artifact_table(output: &mut String, artifacts: &[&crate::catalog::Artifact]) {
    output.push_str(
        "## Artifacts\n\n| ID | Role | Version | Selection | Evidence | Source |\n|---|---|---|---|---|---|\n",
    );
    for artifact in artifacts {
        let _ = writeln!(
            output,
            "| {} | {} | {} | {} | {} | `{}` |",
            markdown_cell(&artifact.id),
            role_name(artifact.role),
            markdown_cell(&artifact.stated_version),
            selection_name(artifact.selection_status),
            evidence_name(artifact.evidence_level),
            markdown_cell(&artifact.source_path)
        );
    }
    output.push('\n');
}

fn render_selected_details(output: &mut String, artifacts: &[&crate::catalog::Artifact]) {
    output.push_str("## Selected Artifact Details\n\n");
    for artifact in artifacts
        .iter()
        .filter(|artifact| artifact.selection_status != SelectionStatus::Unselected)
    {
        let _ = writeln!(output, "### {}\n", artifact.id);
        let _ = writeln!(output, "- Role: {}", role_name(artifact.role));
        let _ = writeln!(output, "- Stated version: {}", artifact.stated_version);
        let _ = writeln!(output, "- Media type: {}", artifact.media_type);
        let _ = writeln!(output, "- Byte size: {}", artifact.byte_size);
        let _ = writeln!(
            output,
            "- Evidence: {}",
            evidence_name(artifact.evidence_level)
        );
        let _ = writeln!(output, "- Derived data: `{}`", artifact.derived_data_path);
        for observation in &artifact.observation {
            let _ = writeln!(
                output,
                "- Observation {}: {} ({}, confidence: {})",
                observation.id,
                markdown_text(&observation.value),
                evidence_name(observation.evidence_level),
                confidence_name(observation.confidence)
            );
        }
        for note in &artifact.notes {
            let _ = writeln!(output, "- Note: {}", markdown_text(note));
        }
        output.push('\n');
    }
}

fn render_hypotheses(output: &mut String, artifacts: &[&crate::catalog::Artifact]) {
    let mut hypotheses: Vec<_> = artifacts
        .iter()
        .flat_map(|artifact| artifact.hypothesis.iter())
        .collect();
    hypotheses.sort_by(|left, right| left.id.cmp(&right.id));

    output.push_str("## Hypotheses\n\n");
    if hypotheses.is_empty() {
        output.push_str("No hypotheses are recorded.\n\n");
        return;
    }
    for hypothesis in hypotheses {
        let _ = writeln!(output, "### {}\n", hypothesis.id);
        let _ = writeln!(output, "{}\n", markdown_text(&hypothesis.statement));
        output.push_str("- Evidence: hypothesis\n");
        let _ = writeln!(
            output,
            "- Evidence basis: {}",
            markdown_text(&hypothesis.evidence)
        );
        let _ = writeln!(
            output,
            "- Confidence: {}",
            confidence_name(hypothesis.confidence)
        );
        let _ = writeln!(
            output,
            "- Confirmation test: {}\n",
            markdown_text(&hypothesis.confirmation_test)
        );
    }
}

fn render_handoff(output: &mut String, catalog: &Catalog) {
    let mut unknowns: Vec<_> = catalog.unknown.iter().collect();
    unknowns.sort_by(|left, right| {
        left.destination_phase
            .cmp(&right.destination_phase)
            .then_with(|| left.priority.cmp(&right.priority))
            .then_with(|| left.id.cmp(&right.id))
    });

    output.push_str("## Prioritized Handoff\n\n");
    if unknowns.is_empty() {
        output.push_str("No unresolved items are recorded.\n");
        return;
    }

    let mut current_phase = None;
    let mut current_priority = None;
    for unknown in unknowns {
        if current_phase != Some(unknown.destination_phase) {
            current_phase = Some(unknown.destination_phase);
            current_priority = None;
            let _ = writeln!(output, "### Phase {}\n", unknown.destination_phase);
        }
        if current_priority != Some(unknown.priority) {
            current_priority = Some(unknown.priority);
            let _ = writeln!(output, "#### {}\n", priority_name(unknown.priority));
        }
        let _ = writeln!(output, "- **{}** (`{}`)", unknown.id, unknown.path);
        let _ = writeln!(output, "  - Artifact: `{}`", unknown.artifact_id);
        let _ = writeln!(
            output,
            "  - Observed: {}",
            unknown
                .observed_properties
                .iter()
                .map(|item| markdown_text(item))
                .collect::<Vec<_>>()
                .join("; ")
        );
        let _ = writeln!(
            output,
            "  - Evidence: {}",
            evidence_name(unknown.evidence_level)
        );
        let _ = writeln!(output, "  - Blocking: {}", yes_no(unknown.blocking));
        let _ = writeln!(output, "  - Reason: {}", markdown_text(&unknown.reason));
        let _ = writeln!(
            output,
            "  - Possible owner: {}",
            markdown_text(&unknown.possible_owner)
        );
        let _ = writeln!(
            output,
            "  - Confirmation test: {}\n",
            markdown_text(&unknown.confirmation_test)
        );
    }
}

fn write_complete_file(path: &Path, content: &str) -> Result<(), std::io::Error> {
    let mut file = OpenOptions::new().write(true).create_new(true).open(path)?;
    file.write_all(content.as_bytes())?;
    file.sync_all()
}

fn temporary_sibling_path(destination: &Path) -> Result<PathBuf, CatalogError> {
    let file_name = destination.file_name().ok_or_else(|| {
        CatalogError::CatalogInvariant(format!(
            "output path must name a file: {}",
            destination.display()
        ))
    })?;
    let sequence = TEMPORARY_FILE_COUNTER.fetch_add(1, Ordering::Relaxed);
    let temporary_name = format!(
        ".{}.{}.{}.tmp",
        file_name.to_string_lossy(),
        std::process::id(),
        sequence
    );
    Ok(destination.with_file_name(temporary_name))
}

fn io_error(path: &Path, source: std::io::Error) -> CatalogError {
    CatalogError::Io {
        path: path.display().to_string(),
        source,
    }
}

fn role_name(role: Role) -> &'static str {
    match role {
        Role::Tower => "tower",
        Role::Station => "station",
        Role::Dongle => "dongle",
    }
}

fn selection_name(selection: SelectionStatus) -> &'static str {
    match selection {
        SelectionStatus::Selected => "selected",
        SelectionStatus::Primary => "primary",
        SelectionStatus::Comparison => "comparison",
        SelectionStatus::Unselected => "unselected",
    }
}

fn evidence_name(evidence: EvidenceLevel) -> &'static str {
    match evidence {
        EvidenceLevel::Verified => "verified",
        EvidenceLevel::Hypothesis => "hypothesis",
        EvidenceLevel::Unknown => "unknown",
    }
}

fn confidence_name(confidence: Confidence) -> &'static str {
    match confidence {
        Confidence::High => "high",
        Confidence::Medium => "medium",
        Confidence::Low => "low",
    }
}

fn priority_name(priority: Priority) -> &'static str {
    match priority {
        Priority::Blocking => "blocking",
        Priority::Required => "required",
        Priority::Informational => "informational",
    }
}

fn yes_no(value: bool) -> &'static str {
    if value { "yes" } else { "no" }
}

fn markdown_cell(value: &str) -> String {
    markdown_text(value).replace('|', "\\|")
}

fn markdown_text(value: &str) -> String {
    value.replace(['\r', '\n'], " ")
}

fn version_key(version: &str) -> Vec<u32> {
    version
        .split('.')
        .map(|part| part.parse::<u32>().unwrap_or_default())
        .collect()
}
